### ISSUE TITLE
About JSP Error

### ISSUE THREAD

**Issue by s5uishida** [herlesupreeth/FHoSS#3]
Hi @herlesupreeth 

When I did the following operation in `20. Add IMS subscription use in FoHSS as follows from the Web GUI` of `VoLTE Setup with Kamailio IMS and Open5GS`, the following error occurred in the WebConsole of FHoSS.

https://open5gs.org/open5gs/docs/tutorial/02-VoLTE-setup/
```
...
And, finally add these IMPUs as implicit set of IMSI derived IMPU in HSS i.e sip:001010123456791@ims.mnc001.mcc001.3gppnetwork.org as follows:

1. Goto to IMPU sip:001010123456791@ims.mnc001.mcc001.3gppnetwork.org
```
The value of IMPU which I used on my environment is the string different from above this.
This operation is `Public User Identity - Search` menu.
```
HTTP Status 500 -
type Exception report

message

description The server encountered an internal error () that prevented it from fulfilling this request.

exception

org.apache.jasper.JasperException: Unable to compile class for JSP

An error occurred at line: 146 in the jsp file: /pages/user/impu_search_result.jsp
Generated servlet error:
The type java.lang.CharSequence cannot be resolved. It is indirectly referenced from required .class files


        org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:84)
        org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:328)
        org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:397)
        org.apache.jasper.compiler.Compiler.compile(Compiler.java:288)
        org.apache.jasper.compiler.Compiler.compile(Compiler.java:267)
        org.apache.jasper.compiler.Compiler.compile(Compiler.java:255)
        org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:556)
        org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:293)
        org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:291)
        org.apache.jasper.servlet.JspServlet.service(JspServlet.java:241)
        javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
        org.apache.struts.action.RequestProcessor.doForward(RequestProcessor.java:1063)
        org.apache.struts.tiles.TilesRequestProcessor.doForward(TilesRequestProcessor.java:263)
        org.apache.struts.action.RequestProcessor.processForwardConfig(RequestProcessor.java:386)
        org.apache.struts.tiles.TilesRequestProcessor.processForwardConfig(TilesRequestProcessor.java:318)
        org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:229)
        org.apache.struts.action.ActionServlet.process(ActionServlet.java:1194)
        org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:432)
        javax.servlet.http.HttpServlet.service(HttpServlet.java:709)
        javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
note The full stack trace of the root cause is available in the Apache Tomcat/5.5.9 logs.
```
Other Search operations will result in similar errors.

`IMS Subscription - Search` menu
```
An error occurred at line: 116 in the jsp file: /pages/user/imsu_search_result.jsp
```
`Private User Identity - Search` menu
```
An error occurred at line: 114 in the jsp file: /pages/user/impi_search_result.jsp
```

Could you know what it occered?

The Java version is as follows.
```
# java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~18.04-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
```
If you find out something, I would be very glad if you could tell me.

Thank you very much in advance.

--Shigeru

**Comment by herlesupreeth** [comment]
Can you please tell me which Ubuntu version you are using? And also the mysql version 

I too faced this issue when i was using Ubuntu 18.04 which comes with older mysql

**Comment by herlesupreeth** [comment]
Recently there was PR merged to enable usage of newer mysql

**Comment by s5uishida** [comment]
Hi @herlesupreeth 

Thank you for your reply.

- Ubuntu 18.04

```
Linux open5gs01 4.15.0-132-lowlatency #136-Ubuntu SMP PREEMPT Tue Jan 12 15:37:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
- MySQL

```
mysql  Ver 14.14 Distrib 5.7.35, for Linux (x86_64) using  EditLine wrapper
```
By the way, regarding the following points, 

`13. Create new mysql database for pcscf, scscf and icscf, populate databases and grant permissions to respective users identified by a password`

```
<mysql> grant delete,insert,select,update on pcscf.* to pcscf@localhost identified by 'heslo';
<mysql> grant delete,insert,select,update on scscf.* to scscf@localhost identified by 'heslo';
<mysql> grant delete,insert,select,update on icscf.* to icscf@localhost identified by 'heslo';
<mysql> grant delete,insert,select,update on icscf.* to provisioning@localhost identified by 'provi';
<mysql> GRANT ALL PRIVILEGES ON pcscf.* TO 'pcscf'@'%' identified by 'heslo';
<mysql> GRANT ALL PRIVILEGES ON scscf.* TO 'scscf'@'%' identified by 'heslo';
<mysql> GRANT ALL PRIVILEGES ON icscf.* TO 'icscf'@'%' identified by 'heslo';
<mysql> GRANT ALL PRIVILEGES ON icscf.* TO 'provisioning'@'%' identified by 'provi';
<mysql> FLUSH PRIVILEGES;
```
The operation was changed as follows. 
```
create user 'pcscf'@'localhost' identified by 'heslo';
create user 'scscf'@'localhost' identified by 'heslo';
create user 'icscf'@'localhost' identified by 'heslo';
create user 'provisioning'@'localhost' identified by 'provi';

create user 'pcscf'@'%' identified by 'heslo';
create user 'scscf'@'%' identified by 'heslo';
create user 'icscf'@'%' identified by 'heslo';
create user 'provisioning'@'%' identified by 'provi';

grant delete,insert,select,update on pcscf.* to pcscf@localhost with grant option;
grant delete,insert,select,update on scscf.* to scscf@localhost with grant option;
grant delete,insert,select,update on icscf.* to icscf@localhost with grant option;
grant delete,insert,select,update on icscf.* to provisioning@localhost with grant option;

GRANT ALL PRIVILEGES ON pcscf.* TO 'pcscf'@'%' with grant option;
GRANT ALL PRIVILEGES ON scscf.* TO 'scscf'@'%' with grant option;
GRANT ALL PRIVILEGES ON icscf.* TO 'icscf'@'%' with grant option;
GRANT ALL PRIVILEGES ON icscf.* TO 'provisioning'@'%' with grant option;

FLUSH PRIVILEGES;
```

**Comment by herlesupreeth** [comment]
True. That guide needs a bit of refresh

**Comment by herlesupreeth** [comment]
@s5uishida The mysql which i am using is the following, please try using that and see whether it solves the above issue

```
mysql --version
mysql  Ver 8.0.26-0ubuntu0.20.04.2 for Linux on x86_64 ((Ubuntu))
```

**Comment by s5uishida** [comment]
Hi @herlesupreeth 

Sorry for the late reply.

When I updated and tried MySQL on Ubuntu 18.04, I got the same JSP error.
The version of MySQL is as follows.
```
mysql  Ver 8.0.26 for Linux on x86_64 (MySQL Community Server - GPL)
```
The reason I'm using Ubuntu 18.04 is that **16. Install RTPEngine** couldn't process dpkg-checkbuilddeps well on Ubuntu 20.04.

If you don't mind, I would be very glad if you could tell me the conditions for a successful setup.

- OS version
- MySQL version
- Kamailio version
- Java version
- RTPEngine version
- etc...

Thank you very much in advance.

**Comment by herlesupreeth** [comment]
@s5uishida I maintain the following repo - https://github.com/herlesupreeth/docker_open5gs (contains Dockerfile for all IMS components + fhoss mentioned in VoLTE guide)

In this, if you follow the Dockerfile you should be able to build RTPEngine on Ubuntu 20.04  - https://github.com/herlesupreeth/docker_open5gs/blob/master/rtpengine/Dockerfile (the same instruction apply when compiling on host machine)

Following are the logs when i run mysql in the above docker environment

```
supreeth@alienware:~$ docker logs mysql 
Waiting for MySQL to start.
 * Stopping MySQL database server mysqld
   ...done.
 * Starting MySQL database server mysqld
   ...done.
2021-09-14T06:14:06.852030Z mysqld_safe Logging to '/var/log/mysql/error.log'.
2021-09-14T06:14:06.869639Z mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
supreeth@alienware:~$ docker exec -ti mysql bash
root@fc70ab96beee:/# mysql --version
mysql  Ver 8.0.26-0ubuntu0.20.04.2 for Linux on x86_64 ((Ubuntu))
root@fc70ab96beee:/# cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
root@fc70ab96beee:/# 

```

And following are the logs when i run fhoss

```
supreeth@alienware:~$ docker logs fhoss
changing: DiameterPeerHSS.xml c3p0.properties hibernate.properties hss.properties log4j.properties 
changing: hss_db.sql hss_db_migrate_as_register.sql hss_db_migrate_dsai.sql userdata.sql 
changing: DiameterPeerHSS.xml c3p0.properties hibernate.properties hss.properties log4j.properties 
mysqld is alive
Building Classpath
Classpath is lib/xml-apis.jar:lib/xercesImpl.jar:lib/xerces-2.4.0.jar:lib/xalan-2.4.0.jar:lib/tomcat-util.jar:lib/tomcat-http.jar:lib/tomcat-coyote.jar:lib/struts.jar:lib/servlets-default.jar:lib/servlet-api.jar:lib/naming-resources.jar:lib/naming-factory.jar:lib/mysql-connector-java-5.1.49-bin.jar:lib/mx4j-3.0.1.jar:lib/log4j.jar:lib/junitee.jar:lib/junit.jar:lib/jta.jar:lib/jsp-api.jar:lib/jmx.jar:lib/jdp.jar:lib/jasper-runtime.jar:lib/jasper-compiler.jar:lib/jasper-compiler-jdt.jar:lib/hibernate3.jar:lib/ehcache-1.1.jar:lib/dom4j-1.6.1.jar:lib/commons-validator.jar:lib/commons-modeler.jar:lib/commons-logging.jar:lib/commons-logging-1.0.4.jar:lib/commons-lang.jar:lib/commons-fileupload.jar:lib/commons-el.jar:lib/commons-digester.jar:lib/commons-collections-3.1.jar:lib/commons-beanutils.jar:lib/cglib-2.1.3.jar:lib/catalina.jar:lib/catalina-optional.jar:lib/c3p0-0.9.1.jar:lib/base64.jar:lib/asm.jar:lib/asm-attrs.jar:lib/antlr-2.7.6.jar:lib/FHoSS.jar:/usr/lib/jvm/jdk1.7.0_80/jre/lib/:log4j.properties:..
[main] INFO  de.fhg.fokus.hss.main.TomcatServer  - Tomcat-Server is started.
[main] INFO  org.apache.catalina.startup.Embedded  - Starting tomcat server
[main] INFO  org.apache.catalina.core.StandardEngine  - Starting Servlet Engine: Apache Tomcat/5.5.9
[main] INFO  org.apache.coyote.http11.Http11Protocol  - Initializing Coyote HTTP/1.1 on http-172.22.0.18-8080
[main] INFO  org.apache.coyote.http11.Http11Protocol  - Starting Coyote HTTP/1.1 on http-172.22.0.18-8080
[main] WARN  org.apache.catalina.connector.MapperListener  - Unknown default host: 172.22.0.18
[main] INFO  org.apache.catalina.core.StandardHost  - XML validation disabled
[main] INFO  de.fhg.fokus.hss.web.servlet.ResponseFilter  - Response Filter Initialisation!
log4j:WARN No appenders could be found for logger (org.apache.catalina.loader.WebappClassLoader).
log4j:WARN Please initialize the log4j system properly.
[main] INFO  org.apache.struts.tiles.TilesPlugin  - Tiles definition factory loaded for module ''.
[main] INFO  org.apache.struts.validator.ValidatorPlugIn  - Loading validation rules file from '/WEB-INF/validator-rules.xml'
[main] INFO  org.apache.struts.validator.ValidatorPlugIn  - Loading validation rules file from '/WEB-INF/validation.xml'
[main] INFO  de.fhg.fokus.hss.main.TomcatServer  - WebConsole of FHoSS was started !
[main] INFO  org.hibernate.cfg.Environment  - Hibernate 3.2.1
[main] INFO  org.hibernate.cfg.Environment  - loaded properties from resource hibernate.properties: {hibernate.c3p0.timeout=3600, hibernate.connection.driver_class=com.mysql.jdbc.Driver, hibernate.connection.isolation=1, hibernate.c3p0.max_statements=0, hibernate.c3p0.max_size=30, hibernate.dialect=org.hibernate.dialect.MySQLDialect, hibernate.c3p0.idle_test_period=1200, hibernate.connection.useUnicode=true, hibernate.c3p0.min_size=1, hibernate.connection.CharSet=utf8, hibernate.connection.username=hss, hibernate.c3p0.acquire_increment=1, hibernate.connection.url=jdbc:mysql://172.22.0.17:3306/hss_db, hibernate.bytecode.use_reflection_optimizer=false, hibernate.connection.password=****, hibernate.connection.characterEncoding=utf8}
[main] INFO  org.hibernate.cfg.Environment  - Bytecode provider name : cglib
[main] INFO  org.hibernate.cfg.Environment  - using JDK 1.4 java.sql.Timestamp handling
[main] INFO  org.hibernate.cfg.Configuration  - configuring from resource: /hibernate.cfg.xml
[main] INFO  org.hibernate.cfg.Configuration  - Configuration resource: /hibernate.cfg.xml
[main] INFO  org.hibernate.cfg.Configuration  - Reading mappings from resource : mappings/ApplicationServer.hbm.xml
[main] INFO  org.hibernate.cfg.HbmBinder  - Mapping class: de.fhg.fokus.hss.db.model.ApplicationServer -> application_server
[main] INFO  org.hibernate.cfg.Configuration  - Reading mappings from resource : mappings/CapabilitiesSet.hbm.xml
[main] INFO  org.hibernate.cfg.HbmBinder  - Mapping class: de.fhg.fokus.hss.db.model.CapabilitiesSet -> capabilities_set
[main] INFO  org.hibernate.cfg.Configuration  - Reading mappings from resource : mappings/Capability.hbm.xml
[main] INFO  org.hibernate.cfg.HbmBinder  - Mapping class: de.fhg.fokus.hss.db.model.Capability -> capability
[main] INFO  org.hibernate.cfg.Configuration  - Reading mappings from resource : mappings/ChargingInfo.hbm.xml
[main] INFO  org.hibernate.cfg.HbmBinder  - Mapping class: de.fhg.fokus.hss.db.model.ChargingInfo -> charging_info
[main] INFO  org.hibernate.cfg.Configuration  - Reading mappings from resource : mappings/DSAI_IMPU.hbm.xml
[main] INFO  org.hibernate.cfg.HbmBinder  - Mapping class: de.fhg.fokus.hss.db.model.DSAI_IMPU -> dsai_impu
[main] INFO  org.hibernate.cfg.Configuration  - Reading mappings from resource : mappings/DSAI_IFC.hbm.xml
[main] INFO  org.hibernate.cfg.HbmBinder  - Mapping class: de.fhg.fokus.hss.db.model.DSAI_IFC -> dsai_ifc
[main] INFO  org.hibernate.cfg.Configuration  - Reading mappings from resource : mappings/DSAI.hbm.xml
[main] INFO  org.hibernate.cfg.HbmBinder  - Mapping class: de.fhg.fokus.hss.db.model.DSAI -> dsai
[main] INFO  org.hibernate.cfg.Configuration  - Reading mappings from resource : mappings/IFC.hbm.xml
[main] INFO  org.hibernate.cfg.HbmBinder  - Mapping class: de.fhg.fokus.hss.db.model.IFC -> ifc
[main] INFO  org.hibernate.cfg.Configuration  - Reading mappings from resource : mappings/IMPI_IMPU.hbm.xml
[main] INFO  org.hibernate.cfg.HbmBinder  - Mapping class: de.fhg.fokus.hss.db.model.IMPI_IMPU -> impi_impu
[main] INFO  org.hibernate.cfg.Configuration  - Reading mappings from resource : mappings/IMPI.hbm.xml
[main] INFO  org.hibernate.cfg.HbmBinder  - Mapping class: de.fhg.fokus.hss.db.model.IMPI -> impi
[main] INFO  org.hibernate.cfg.Configuration  - Reading mappings from resource : mappings/IMPU.hbm.xml
[main] INFO  org.hibernate.cfg.HbmBinder  - Mapping class: de.fhg.fokus.hss.db.model.IMPU -> impu
[main] INFO  org.hibernate.cfg.Configuration  - Reading mappings from resource : mappings/IMPU_VisitedNetwork.hbm.xml
[main] INFO  org.hibernate.cfg.HbmBinder  - Mapping class: de.fhg.fokus.hss.db.model.IMPU_VisitedNetwork -> impu_visited_network
[main] INFO  org.hibernate.cfg.Configuration  - Reading mappings from resource : mappings/IMSU.hbm.xml
[main] INFO  org.hibernate.cfg.HbmBinder  - Mapping class: de.fhg.fokus.hss.db.model.IMSU -> imsu
[main] INFO  org.hibernate.cfg.Configuration  - Reading mappings from resource : mappings/Preferred_SCSCF_Set.hbm.xml
[main] INFO  org.hibernate.cfg.HbmBinder  - Mapping class: de.fhg.fokus.hss.db.model.Preferred_SCSCF_Set -> preferred_scscf_set
[main] INFO  org.hibernate.cfg.Configuration  - Reading mappings from resource : mappings/CxEvents.hbm.xml
[main] INFO  org.hibernate.cfg.HbmBinder  - Mapping class: de.fhg.fokus.hss.db.model.CxEvents -> cx_events
[main] INFO  org.hibernate.cfg.Configuration  - Reading mappings from resource : mappings/Shared_IFC_Set.hbm.xml
[main] INFO  org.hibernate.cfg.HbmBinder  - Mapping class: de.fhg.fokus.hss.db.model.Shared_IFC_Set -> shared_ifc_set
[main] INFO  org.hibernate.cfg.Configuration  - Reading mappings from resource : mappings/ShNotification.hbm.xml
[main] INFO  org.hibernate.cfg.HbmBinder  - Mapping class: de.fhg.fokus.hss.db.model.ShNotification -> sh_notification
[main] INFO  org.hibernate.cfg.Configuration  - Reading mappings from resource : mappings/ShSubscription.hbm.xml
[main] INFO  org.hibernate.cfg.HbmBinder  - Mapping class: de.fhg.fokus.hss.db.model.ShSubscription -> sh_subscription
[main] INFO  org.hibernate.cfg.Configuration  - Reading mappings from resource : mappings/SP_IFC.hbm.xml
[main] INFO  org.hibernate.cfg.HbmBinder  - Mapping class: de.fhg.fokus.hss.db.model.SP_IFC -> sp_ifc
[main] INFO  org.hibernate.cfg.Configuration  - Reading mappings from resource : mappings/SP_Shared_IFC_Set.hbm.xml
[main] INFO  org.hibernate.cfg.HbmBinder  - Mapping class: de.fhg.fokus.hss.db.model.SP_Shared_IFC_Set -> sp_shared_ifc_set
[main] INFO  org.hibernate.cfg.Configuration  - Reading mappings from resource : mappings/SP.hbm.xml
[main] INFO  org.hibernate.cfg.HbmBinder  - Mapping class: de.fhg.fokus.hss.db.model.SP -> sp
[main] INFO  org.hibernate.cfg.Configuration  - Reading mappings from resource : mappings/SPT.hbm.xml
[main] INFO  org.hibernate.cfg.HbmBinder  - Mapping class: de.fhg.fokus.hss.db.model.SPT -> spt
[main] INFO  org.hibernate.cfg.Configuration  - Reading mappings from resource : mappings/TP.hbm.xml
[main] INFO  org.hibernate.cfg.HbmBinder  - Mapping class: de.fhg.fokus.hss.db.model.TP -> tp
[main] INFO  org.hibernate.cfg.Configuration  - Reading mappings from resource : mappings/VisitedNetwork.hbm.xml
[main] INFO  org.hibernate.cfg.HbmBinder  - Mapping class: de.fhg.fokus.hss.db.model.VisitedNetwork -> visited_network
[main] INFO  org.hibernate.cfg.Configuration  - Reading mappings from resource : mappings/RepositoryData.hbm.xml
[main] INFO  org.hibernate.cfg.HbmBinder  - Mapping class: de.fhg.fokus.hss.db.model.RepositoryData -> repository_data
[main] INFO  org.hibernate.cfg.Configuration  - Reading mappings from resource : mappings/AliasesRepositoryData.hbm.xml
[main] INFO  org.hibernate.cfg.HbmBinder  - Mapping class: de.fhg.fokus.hss.db.model.AliasesRepositoryData -> aliases_repository_data
[main] INFO  org.hibernate.cfg.Configuration  - Reading mappings from resource : mappings/Zh_USS.hbm.xml
[main] INFO  org.hibernate.cfg.HbmBinder  - Mapping class: de.fhg.fokus.hss.db.model.Zh_USS -> zh_uss
[main] INFO  org.hibernate.cfg.Configuration  - Configured SessionFactory: foo
[main] INFO  org.hibernate.connection.C3P0ConnectionProvider  - C3P0 using driver: com.mysql.jdbc.Driver at URL: jdbc:mysql://172.22.0.17:3306/hss_db
[main] INFO  org.hibernate.connection.C3P0ConnectionProvider  - Connection properties: {useUnicode=true, user=hss, password=****, CharSet=utf8, autocommit=false, characterEncoding=utf8}
[main] INFO  org.hibernate.connection.C3P0ConnectionProvider  - autocommit mode: false
[main] INFO  com.mchange.v2.log.MLog  - MLog clients using log4j logging.
[main] INFO  com.mchange.v2.c3p0.C3P0Registry  - Initializing c3p0-0.9.1 [built 16-January-2007 14:46:42; debug? true; trace: 10]
[main] INFO  org.hibernate.connection.C3P0ConnectionProvider  - JDBC isolation level: READ_UNCOMMITTED
[main] INFO  com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource  - Initializing c3p0 pool... com.mchange.v2.c3p0.PoolBackedDataSource@7945bf72 [ connectionPoolDataSource -> com.mchange.v2.c3p0.WrapperConnectionPoolDataSource@4826856b [ acquireIncrement -> 1, acquireRetryAttempts -> 60, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, debugUnreturnedConnectionStackTraces -> false, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, identityToken -> 1bqx2c2aj1qyv1pe1qgnnlh|42e95cbf, idleConnectionTestPeriod -> 1200, initialPoolSize -> 1, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 3600, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 30, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 1, nestedDataSource -> com.mchange.v2.c3p0.DriverManagerDataSource@1a5e45b1 [ description -> null, driverClass -> null, factoryClassLocation -> null, identityToken -> 1bqx2c2aj1qyv1pe1qgnnlh|14add9ad, jdbcUrl -> jdbc:mysql://172.22.0.17:3306/hss_db, properties -> {useUnicode=true, user=******, password=******, CharSet=utf8, autocommit=false, characterEncoding=utf8} ], preferredTestQuery -> null, propertyCycle -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, usesTraditionalReflectiveProxies -> false; userOverrides: {} ], dataSourceName -> null, factoryClassLocation -> null, identityToken -> 1bqx2c2aj1qyv1pe1qgnnlh|54bc9cb5, numHelperThreads -> 3 ]
Tue Sep 14 08:14:23 CEST 2021 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
Tue Sep 14 08:14:23 CEST 2021 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[main] INFO  org.hibernate.cfg.SettingsFactory  - RDBMS: MySQL, version: 8.0.26-0ubuntu0.20.04.2
[main] INFO  org.hibernate.cfg.SettingsFactory  - JDBC driver: MySQL Connector Java, version: mysql-connector-java-5.1.49 ( Revision: ad86f36e100e104cd926c6b81c8cab9565750116 )
[main] INFO  org.hibernate.dialect.Dialect  - Using dialect: org.hibernate.dialect.MySQLDialect
[main] INFO  org.hibernate.transaction.TransactionFactoryFactory  - Using default transaction strategy (direct JDBC transactions)
[main] INFO  org.hibernate.transaction.TransactionManagerLookupFactory  - No TransactionManagerLookup configured (in JTA environment, use of read-write or transactional second-level cache is not recommended)
[main] INFO  org.hibernate.cfg.SettingsFactory  - Automatic flush during beforeCompletion(): disabled
[main] INFO  org.hibernate.cfg.SettingsFactory  - Automatic session close at end of transaction: disabled
[main] INFO  org.hibernate.cfg.SettingsFactory  - JDBC batch size: 15
[main] INFO  org.hibernate.cfg.SettingsFactory  - JDBC batch updates for versioned data: disabled
[main] INFO  org.hibernate.cfg.SettingsFactory  - Scrollable result sets: enabled
[main] INFO  org.hibernate.cfg.SettingsFactory  - JDBC3 getGeneratedKeys(): enabled
[main] INFO  org.hibernate.cfg.SettingsFactory  - Connection release mode: auto
[main] INFO  org.hibernate.cfg.SettingsFactory  - Maximum outer join fetch depth: 2
[main] INFO  org.hibernate.cfg.SettingsFactory  - Default batch fetch size: 1
[main] INFO  org.hibernate.cfg.SettingsFactory  - Generate SQL with comments: disabled
[main] INFO  org.hibernate.cfg.SettingsFactory  - Order SQL updates by primary key: disabled
[main] INFO  org.hibernate.cfg.SettingsFactory  - Query translator: org.hibernate.hql.ast.ASTQueryTranslatorFactory
[main] INFO  org.hibernate.hql.ast.ASTQueryTranslatorFactory  - Using ASTQueryTranslatorFactory
[main] INFO  org.hibernate.cfg.SettingsFactory  - Query language substitutions: {}
[main] INFO  org.hibernate.cfg.SettingsFactory  - JPA-QL strict compliance: disabled
[main] INFO  org.hibernate.cfg.SettingsFactory  - Second-level cache: enabled
[main] INFO  org.hibernate.cfg.SettingsFactory  - Query cache: disabled
[main] INFO  org.hibernate.cfg.SettingsFactory  - Cache provider: org.hibernate.cache.NoCacheProvider
[main] INFO  org.hibernate.cfg.SettingsFactory  - Optimize cache for minimal puts: disabled
[main] INFO  org.hibernate.cfg.SettingsFactory  - Structured second-level cache entries: disabled
[main] INFO  org.hibernate.cfg.SettingsFactory  - Statistics: disabled
[main] INFO  org.hibernate.cfg.SettingsFactory  - Deleted entity synthetic identifier rollback: disabled
[main] INFO  org.hibernate.cfg.SettingsFactory  - Default entity-mode: pojo
[main] INFO  org.hibernate.impl.SessionFactoryImpl  - building session factory
[main] INFO  org.hibernate.impl.SessionFactoryObjectFactory  - Factory name: foo
[main] INFO  org.hibernate.util.NamingHelper  - JNDI InitialContext properties:{}
[main] INFO  org.hibernate.impl.SessionFactoryObjectFactory  - Bound factory to JNDI name: foo
[main] WARN  org.hibernate.impl.SessionFactoryObjectFactory  - InitialContext did not implement EventContext
[main] INFO  de.fhg.fokus.diameter.DiameterPeer.DiameterPeer  - Bean style constructor called, don't forget to configure!
[main] INFO  de.fhg.fokus.diameter.DiameterPeer.DiameterPeer  - FQDN: hss.ims.mnc001.mcc001.3gppnetwork.org
[main] INFO  de.fhg.fokus.diameter.DiameterPeer.DiameterPeer  - Realm: ims.mnc001.mcc001.3gppnetwork.org
[main] INFO  de.fhg.fokus.diameter.DiameterPeer.DiameterPeer  - Vendor_ID : 10415
[main] INFO  de.fhg.fokus.diameter.DiameterPeer.DiameterPeer  - Product Name: JavaDiameterPeer
[main] INFO  de.fhg.fokus.diameter.DiameterPeer.DiameterPeer  - AcceptUnknwonPeers: true
[main] INFO  de.fhg.fokus.diameter.DiameterPeer.DiameterPeer  - DropUnknownOnDisconnect: true
[main] INFO  de.fhg.fokus.hss.main.HSSContainer  - 
Type "exit" to stop FHoSS!
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.checkBounds(String.java:371)
	at java.lang.String.<init>(String.java:535)
	at de.fhg.fokus.hss.main.HSSContainer.waitForExit(HSSContainer.java:137)
	at de.fhg.fokus.hss.main.HSSContainer.main(HSSContainer.java:111)
supreeth@alienware:~$ docker exec -ti fhoss bash
root@10dcc2204266:/#
root@10dcc2204266:/# cd /opt/OpenIMSCore/FHoSS/
root@10dcc2204266:/opt/OpenIMSCore/FHoSS# git br
git: 'br' is not a git command. See 'git --help'.

The most similar commands are
	branch
	var
root@10dcc2204266:/opt/OpenIMSCore/FHoSS# git branch
* auth_fix_exp
  master
root@10dcc2204266:/opt/OpenIMSCore/FHoSS# git remote -v
origin	https://github.com/herlesupreeth/FHoSS (fetch)
origin	https://github.com/herlesupreeth/FHoSS (push)
root@10dcc2204266:/opt/OpenIMSCore/FHoSS# 

```

Btw, the fhoss is compiled from auth_fix_exp branch but there is no difference from the master branch in terms of mysql connection

I am able to do a search for "IMS subscription" without any errors

![image](https://user-images.githubusercontent.com/4115839/133205818-dc985556-bfcb-4fd7-867b-bee429b2b9d1.png)


Let me know if you still face issues

**Comment by s5uishida** [comment]
Hi @herlesupreeth 

Thank you very much for your reply.

The **Search facilities** works now by changing java from openjdk version "1.8.0_292" to java version "1.7.0_80".
I will try the next step.

Thanks!
