### ISSUE TITLE
- Error initializing endpoint

### ISSUE THREAD

**Issue by faratell** [herlesupreeth/FHoSS#8]
I installed FHoSS on ubuntu 22.04 and accessed its web interface and set simcard information. but noe when run ./hss.sh have this error:
./hss.sh
Building Classpath
Classpath is lib/xml-apis.jar:lib/xercesImpl.jar:lib/xerces-2.4.0.jar:lib/xalan-2.4.0.jar:lib/tomcat-util.jar:lib/tomcat-http.jar:lib/tomcat-coyote.jar:lib/struts.jar:lib/servlets-default.jar:lib/servlet-api.jar:lib/naming-resources.jar:lib/naming-factory.jar:lib/mysql-connector-java-5.1.49-bin.jar:lib/mx4j-3.0.1.jar:lib/log4j.jar:lib/junit.jar:lib/junitee.jar:lib/jta.jar:lib/jsp-api.jar:lib/jmx.jar:lib/jdp.jar:lib/jasper-runtime.jar:lib/jasper-compiler-jdt.jar:lib/jasper-compiler.jar:lib/hibernate3.jar:lib/FHoSS.jar:lib/ehcache-1.1.jar:lib/dom4j-1.6.1.jar:lib/commons-validator.jar:lib/commons-modeler.jar:lib/commons-logging.jar:lib/commons-logging-1.0.4.jar:lib/commons-lang.jar:lib/commons-fileupload.jar:lib/commons-el.jar:lib/commons-digester.jar:lib/commons-collections-3.1.jar:lib/commons-beanutils.jar:lib/cglib-2.1.3.jar:lib/catalina-optional.jar:lib/catalina.jar:lib/c3p0-0.9.1.jar:lib/base64.jar:lib/asm.jar:lib/asm-attrs.jar:lib/antlr-2.7.6.jar:/usr/lib/jvm/jdk1.7.0_80/jre/lib/:log4j.properties:..
[main] INFO  de.fhg.fokus.hss.main.TomcatServer  - Tomcat-Server is started.
[main] INFO  org.apache.catalina.startup.Embedded  - Starting tomcat server
[main] INFO  org.apache.catalina.core.StandardEngine  - Starting Servlet Engine: Apache Tomcat/5.5.9
[main] ERROR org.apache.coyote.http11.Http11Protocol  - Error initializing endpoint
java.net.BindException: Address already in use:8080
	at org.apache.tomcat.util.net.PoolTcpEndpoint.initEndpoint(PoolTcpEndpoint.java:297)
	at org.apache.coyote.http11.Http11Protocol.init(Http11Protocol.java:142)
	at org.apache.catalina.connector.Connector.initialize(Connector.java:928)
	at org.apache.catalina.startup.Embedded.start(Embedded.java:794)
	at de.fhg.fokus.hss.main.TomcatServer.startTomcat(TomcatServer.java:128)
	at de.fhg.fokus.hss.main.HSSContainer.<init>(HSSContainer.java:74)
	at de.fhg.fokus.hss.main.HSSContainer.main(HSSContainer.java:110)
[main] ERROR de.fhg.fokus.hss.main.HSSContainer  - Exception occured during starting Tomcat!
Exiting from HSS...
LifecycleException:  Protocol handler initialization failed: java.net.BindException: Address already in use:8080
	at org.apache.catalina.connector.Connector.initialize(Connector.java:930)
	at org.apache.catalina.startup.Embedded.start(Embedded.java:794)
	at de.fhg.fokus.hss.main.TomcatServer.startTomcat(TomcatServer.java:128)
	at de.fhg.fokus.hss.main.HSSContainer.<init>(HSSContainer.java:74)
	at de.fhg.fokus.hss.main.HSSContainer.main(HSSContainer.java:110)

**Comment by faratell** [comment]
My problem is solved. Thanks
