### ISSUE TITLE
Unable to initialize TldLocationsCache: XML parsing error on file /WEB-INF/struts-logic.tld

### ISSUE THREAD

**Issue by kishanecosmob** [herlesupreeth/FHoSS#9]
@herlesupreeth 

We tried to install FHoSS with your latest repo java_1.8 but we are getting the below error.

[http-127.0.0.1-8080-Processor4] ERROR org.apache.catalina.core.ContainerBase.[null].[127.0.0.1].[/hss.web.console].[jsp]  - Servlet.service() for servlet jsp threw exception
org.apache.jasper.JasperException: Unable to initialize TldLocationsCache: XML parsing error on file /WEB-INF/struts-logic.tld
        at org.apache.jasper.compiler.TldLocationsCache.init(TldLocationsCache.java:252)
        at org.apache.jasper.compiler.TldLocationsCache.getLocation(TldLocationsCache.java:223)
        at org.apache.jasper.JspCompilationContext.getTldLocation(JspCompilationContext.java:519)
        at org.apache.jasper.compiler.Parser.parseTaglibDirective(Parser.java:417)
        at org.apache.jasper.compiler.Parser.parseDirective(Parser.java:483)
        at org.apache.jasper.compiler.Parser.parseElements(Parser.java:1543)
        at org.apache.jasper.compiler.Parser.parse(Parser.java:126)
        at org.apache.jasper.compiler.ParserController.doParse(ParserController.java:211)
        at org.apache.jasper.compiler.ParserController.parse(ParserController.java:100)
        at org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:146)
        at org.apache.jasper.compiler.Compiler.compile(Compiler.java:286)
        at org.apache.jasper.compiler.Compiler.compile(Compiler.java:267)
        at org.apache.jasper.compiler.Compiler.compile(Compiler.java:255)
        at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:556)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:293)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:291)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:241)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:252)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:178)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:126)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:105)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:107)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:148)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.processConnection(Http11Protocol.java:744)
        at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:527)
        at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:80)
        at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:684)
        at java.lang.Thread.run(Thread.java:750)
        
        Can you help me with the resolution?  
        
        
![Screenshot from 2024-12-18 17-26-47](https://github.com/user-attachments/assets/14f711b7-a40b-42c9-bd00-a29a4f4fb7dc)

**Comment by herlesupreeth** [comment]
I would recommend using PyHSS instead.

As far as I know FHoSS does not work with Java v1.8

**Comment by kishanecosmob** [comment]
@herlesupreeth 
Thanks for the update.

I also tried Java 1.7.0_80, but in the search function, clicking on a user does not retrieve any data; it only displays a white blank screen. Additionally, some other functions in the search are not working.

![Screenshot from 2024-12-25 10-00-51](https://github.com/user-attachments/assets/5975f10e-bf63-4fa9-ae52-d02764a46613)
![Screenshot from 2024-12-25 10-00-56](https://github.com/user-attachments/assets/ae59d536-ad46-4e16-922f-ba6f0e503915)

Can you help with this issue?

**Comment by herlesupreeth** [comment]
Please re-read and do not skip even a single step in Step 19 of this guide - https://open5gs.org/open5gs/docs/tutorial/02-VoLTE-setup/
